a few bugfixes for instdir

diff --git a/Bcps/configure b/Bcps/configure
--- a/Bcps/configure
+++ b/Bcps/configure
@@ -20526,9 +20526,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Bcps with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Bcps with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Bcps/README; then
+		     coin_has_bcps=installed
+		     BCPSINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -20590,13 +20591,30 @@ fi
 if test $coin_has_bcps = installed; then
   echo "$as_me:$LINENO: result: installed in $BCPSINSTDIR" >&5
 echo "${ECHO_T}installed in $BCPSINSTDIR" >&6
-  # Check for header
+  if test -r $BCPSINSTDIR/share/doc/coin/Bcps/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $BCPSINSTDIR/share/doc/coin/Bcps/README should be available if Bcps is installed" >&5
+echo "$as_me: error: $BCPSINSTDIR/share/doc/coin/Bcps/README should be available if Bcps is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_bcps" >&5
 echo "${ECHO_T}$coin_has_bcps" >&6
+  if test $coin_has_bcps != notGiven &&
+     test $coin_has_bcps != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Bcps" >&5
+echo $ECHO_N "checking for source code location of Bcps... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $BCPSSRCDIR" >&5
+echo "${ECHO_T}$BCPSSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Bcps" >&5
+echo $ECHO_N "checking for object code location of Bcps... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $BCPSOBJDIR" >&5
+echo "${ECHO_T}$BCPSOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project CoinUtils" >&5
@@ -20692,9 +20710,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of CoinUtils with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of CoinUtils with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/CoinUtils/README; then
+		     coin_has_coinutils=installed
+		     COINUTILSINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -20756,13 +20775,30 @@ fi
 if test $coin_has_coinutils = installed; then
   echo "$as_me:$LINENO: result: installed in $COINUTILSINSTDIR" >&5
 echo "${ECHO_T}installed in $COINUTILSINSTDIR" >&6
-  # Check for header
+  if test -r $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README should be available if CoinUtils is installed" >&5
+echo "$as_me: error: $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README should be available if CoinUtils is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_coinutils" >&5
 echo "${ECHO_T}$coin_has_coinutils" >&6
+  if test $coin_has_coinutils != notGiven &&
+     test $coin_has_coinutils != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of CoinUtils" >&5
+echo $ECHO_N "checking for source code location of CoinUtils... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COINUTILSSRCDIR" >&5
+echo "${ECHO_T}$COINUTILSSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of CoinUtils" >&5
+echo $ECHO_N "checking for object code location of CoinUtils... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COINUTILSOBJDIR" >&5
+echo "${ECHO_T}$COINUTILSOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Alps" >&5
@@ -20858,9 +20894,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Alps with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Alps with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Alps/README; then
+		     coin_has_alps=installed
+		     ALPSINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -20922,13 +20959,30 @@ fi
 if test $coin_has_alps = installed; then
   echo "$as_me:$LINENO: result: installed in $ALPSINSTDIR" >&5
 echo "${ECHO_T}installed in $ALPSINSTDIR" >&6
-  # Check for header
+  if test -r $ALPSINSTDIR/share/doc/coin/Alps/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $ALPSINSTDIR/share/doc/coin/Alps/README should be available if Alps is installed" >&5
+echo "$as_me: error: $ALPSINSTDIR/share/doc/coin/Alps/README should be available if Alps is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_alps" >&5
 echo "${ECHO_T}$coin_has_alps" >&6
+  if test $coin_has_alps != notGiven &&
+     test $coin_has_alps != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Alps" >&5
+echo $ECHO_N "checking for source code location of Alps... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $ALPSSRCDIR" >&5
+echo "${ECHO_T}$ALPSSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Alps" >&5
+echo $ECHO_N "checking for object code location of Alps... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $ALPSOBJDIR" >&5
+echo "${ECHO_T}$ALPSOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Clp" >&5
@@ -21024,9 +21078,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Clp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Clp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Clp/README; then
+		     coin_has_clp=installed
+		     CLPINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -21088,13 +21143,30 @@ fi
 if test $coin_has_clp = installed; then
   echo "$as_me:$LINENO: result: installed in $CLPINSTDIR" >&5
 echo "${ECHO_T}installed in $CLPINSTDIR" >&6
-  # Check for header
+  if test -r $CLPINSTDIR/share/doc/coin/Clp/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $CLPINSTDIR/share/doc/coin/Clp/README should be available if Clp is installed" >&5
+echo "$as_me: error: $CLPINSTDIR/share/doc/coin/Clp/README should be available if Clp is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_clp" >&5
 echo "${ECHO_T}$coin_has_clp" >&6
+  if test $coin_has_clp != notGiven &&
+     test $coin_has_clp != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Clp" >&5
+echo $ECHO_N "checking for source code location of Clp... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CLPSRCDIR" >&5
+echo "${ECHO_T}$CLPSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Clp" >&5
+echo $ECHO_N "checking for object code location of Clp... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CLPOBJDIR" >&5
+echo "${ECHO_T}$CLPOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Cgl" >&5
@@ -21190,9 +21262,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Cgl with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Cgl with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Cgl/README; then
+		     coin_has_cgl=installed
+		     CGLINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -21254,13 +21327,30 @@ fi
 if test $coin_has_cgl = installed; then
   echo "$as_me:$LINENO: result: installed in $CGLINSTDIR" >&5
 echo "${ECHO_T}installed in $CGLINSTDIR" >&6
-  # Check for header
+  if test -r $CGLINSTDIR/share/doc/coin/Cgl/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $CGLINSTDIR/share/doc/coin/Cgl/README should be available if Cgl is installed" >&5
+echo "$as_me: error: $CGLINSTDIR/share/doc/coin/Cgl/README should be available if Cgl is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_cgl" >&5
 echo "${ECHO_T}$coin_has_cgl" >&6
+  if test $coin_has_cgl != notGiven &&
+     test $coin_has_cgl != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Cgl" >&5
+echo $ECHO_N "checking for source code location of Cgl... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CGLSRCDIR" >&5
+echo "${ECHO_T}$CGLSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Cgl" >&5
+echo $ECHO_N "checking for object code location of Cgl... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CGLOBJDIR" >&5
+echo "${ECHO_T}$CGLOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Osi" >&5
@@ -21356,9 +21446,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Osi with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Osi with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Osi/README; then
+		     coin_has_osi=installed
+		     OSIINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -21420,13 +21511,30 @@ fi
 if test $coin_has_osi = installed; then
   echo "$as_me:$LINENO: result: installed in $OSIINSTDIR" >&5
 echo "${ECHO_T}installed in $OSIINSTDIR" >&6
-  # Check for header
+  if test -r $OSIINSTDIR/share/doc/coin/Osi/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $OSIINSTDIR/share/doc/coin/Osi/README should be available if Osi is installed" >&5
+echo "$as_me: error: $OSIINSTDIR/share/doc/coin/Osi/README should be available if Osi is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_osi" >&5
 echo "${ECHO_T}$coin_has_osi" >&6
+  if test $coin_has_osi != notGiven &&
+     test $coin_has_osi != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Osi" >&5
+echo $ECHO_N "checking for source code location of Osi... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $OSISRCDIR" >&5
+echo "${ECHO_T}$OSISRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Osi" >&5
+echo $ECHO_N "checking for object code location of Osi... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $OSIOBJDIR" >&5
+echo "${ECHO_T}$OSIOBJDIR" >&6
+  fi
 fi
 
 
